# Generated by Django 4.2.3 on 2023-10-10 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate_yeild',
            name='username',
        ),
        migrations.RemoveField(
            model_name='crop_productions',
            name='username',
        ),
        migrations.RemoveField(
            model_name='loan_calculate',
            name='username',
        ),
        migrations.AddField(
            model_name='calculate_yeild',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crop_productions',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan_calculate',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
