# Generated by Django 4.2.3 on 2023-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_remove_calculate_yeild_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_calculate',
            name='profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan_calculate',
            name='totalCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan_calculate',
            name='totalProduction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan_calculate',
            name='annual_interest',
            field=models.IntegerField(null=True),
        ),
    ]
