# Generated by Django 4.2.3 on 2023-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_loan_calculate_profit_loan_calculate_totalcost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_calculate',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='loan_calculate',
            name='totalCost',
        ),
        migrations.RemoveField(
            model_name='loan_calculate',
            name='totalProduction',
        ),
        migrations.AddField(
            model_name='crop_productions',
            name='profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crop_productions',
            name='totalCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crop_productions',
            name='totalProduction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crop_productions',
            name='totalRevenue',
            field=models.IntegerField(null=True),
        ),
    ]
